config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#top'
  get "home/about" => "home#about"
  resources :books, only: [:new,:create,:index,:show,:destroy,:edit,:update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

	validates :title, presence: true
	validates :body,
	presence: true ,
	length: { maximum: 200 }

	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :name,
  presence: true,
  length: { in: 2..20 }

	validates :email,
	presence: true

	validates :encrypted_password,
	presence: true

  validates :introduction,
  length: { maximum: 50 }


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books ,dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  	before_action :configure_permitted_parameters, if: :devise_controller?


  	def after_sign_in_path_for(resource) 
    user_path(resource)
  	end




  	def after_sign_out_path_for(resource) 
    root_path
  	end


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

		before_action :authenticate_user!


	def new

	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
		flash[:notice1]="Book was successfully created."
		redirect_to book_path(@book.id)
		else
		@books=Book.all
		@user = current_user
    	render 'index'
	    end

	end

	def index
		@book = Book.new
		@books = Book.all
		@user = current_user
	end

	def show
		@book = Book.new
		@book_1 = Book.find(params[:id])
		@user = User.find(@book_1.user.id)
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy

		redirect_to books_path
	end

	def edit
		@book = Book.find(params[:id])
		if @book.user.id != current_user.id
			redirect_to books_path
		end
	end

	def update
		@book=Book.find(params[:id])
		if @book.update(book_params)
		flash[:notice2] = "Book was successfully update."
		redirect_to book_path(@book.id)
		else
		render 'edit'
		end
	end


	private
	def book_params
		params.require(:book).permit(:title,:body)
	end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
  end

  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!


  def show
    @book = Book.new
  	@user = User.find(params[:id])
    @books =Book.where(user_id:@user.id)
  end

  def index
    @book = Book.new
  	@users = User.all
    @user = current_user

  end

  def edit
  	@user = User.find(params[:id])

    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end

  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
    flash[:notice3] = "You have updated user successfully."
  	redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  private
  def user_params
  	params.require(:user).permit(:name,:profile_image,:introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
            <h2>New book</h2>
            <%= form_for(book) do |f| %>

                <label class = "">Title</label>
                    <div class="newbook-text">
                        <%= f.text_field :title,class:"form-control m-4" %>
                    </div>


                <label class = "">Opinion</label>
                    <div class="newbook-text">
                        <%= f.text_area :body,class:"form-control m-4"  %>
                    </div>
                    <div class="create-book">
                        <%= f.submit "Create Book", class:"btn btn-primary btn-block"%>
                    </div>
            <% end %>

app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<div class ="col-md-6 col-md-offset-3">
            <div class ="edit-book">
			<h2>Editing Book</h2>

<!-- エラーメッセージ -->
    <div id="error_explanation">
        <% if @book.errors.any? %>
            <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
        <% end %>
    </div>


            <%= form_for(@book) do |f| %>

                <label class = "">Title</label>
                    <div class="edit-text">
                        <%= f.text_field :title,class:"form-control m-4" %>
                    </div>


                <label class = "">Opinion</label>
                    <div class="edit-text">
                        <%= f.text_area :body,class:"form-control m-4"  %>
                    </div>
                    <div class="update-book">
                        <%= f.submit "Update book", class:"btn btn-primary btn-block"%>
                    </div>
                    <%=link_to "Show",book_path(@book.id)%>|

                    <%= link_to "Back",books_path%>
            <% end %>
		</div>
    </div>
	</div>
</div>

app/views/books/index.html.erb
<div class="container">
    <!-- エラーメッセージ -->
    <div id="error_explanation">
        <% if @book.errors.any? %>
            <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
        <% end %>
    </div>

    <div class="row">
        <div class="col-xs-3">

            <!-- プロフィール -->

        <%= render 'users/info', user: @user %>
            <!-- プロフィール -->

            <!-- 新規投稿 -->
        <%= render 'books/new', book: @book %>
            <!-- 新規投稿 -->


        </div>
            <!-- 投稿一覧画面 -->
        <div class="col-xs-9">
            <h2>Books</h2>

                <table class ="table table-hover">
                    <thead>
                        <tr>
                            <th></th><th>Title</th> <th>Opinion</th><th colspan="3"></th>
                        </tr>
                    </thead>

                   <tbody>
                             <% @books.each do |book| %>
                                <tr>
                                    <td><%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %></td>
                                    <td>
                                        <%= link_to "#{book.title}",book_path(book.id)%>
                                    </td>
                                    <td>
                                        <%= book.body %>
                                    </td>
                                </tr>
                            <% end %>
                    </tbody>
                </table>
        </div>
    </div>
</div>


            <!-- 投稿一覧画面 -->

app/views/books/show.html.erb
<div class="container">
    <div class="row content">
        <div class="col-xs-3">
    <% if flash[:notice1] %>
      <div class="flash">
        <%= flash[:notice1] %>
      </div>
    <% end %>

    <% if flash[:notice2] %>
      <div class="flash">
        <%= flash[:notice2] %>
      </div>
    <% end %>
            <!-- プロフィール -->
            <%= render 'users/info', user: @user %>
            <!-- プロフィール -->

            <!-- 新規投稿 -->

            <%= render 'books/new', book: @book %>

            <!-- 新規投稿 -->

        </div>




            <!-- 投稿一覧画面 -->
        <div class="col-xs-9">
            <h2>Book detail</h2>

                <table class ="table ">

                   <tbody>
                                <tr>
                                    <td>
                                        <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
                                        <br>
                                        <%= link_to "#{@user.name}", user_path(@user.id) %></td>
                                    <td>
                                        <%= link_to @book_1.title,book_path(@book_1.id)%>
                                    </td>
                                    <td>
                                        <%= @book_1.body %>
                                    </td>

                                        <% if @book_1.user.id == current_user.id %>
                                    <td>
                                        <%= link_to "Edit", edit_book_path(@book_1), class: "btn-sm btn-success" %>
                                    </td>
                                    <td>
                                        <%= link_to "Destroy", book_path(@book_1), method: :delete, class: "btn-sm btn-danger","data-confirm" => "本当に削除しますか？" %>
                                    </td>
                                        <% end %>
                                </tr>

                    </tbody>
                </table>
        </div>
    </div>
</div>

app/views/home/about.html.erb
<div class = "container">


			<h1 class="about-text">welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span> Bookers!!</h1>


</div>

app/views/home/top.html.erb
<div class = "container">
	<div class = "row">

    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>


		<div class="col-md-offset-3 col-md-6">

			<h1>welcome to <span class="glyphicon glyphicon-book" aria-hidden="true"></span> Bookers  !!</h1>
			<p>In <span class="glyphicon glyphicon-book" aria-hidden="true"></span><strong>Bookers,</strong></p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about various books!</p>

			<div class ="btn-wrapper">
				<div class = "row-home">
					<%= link_to "Login", new_user_session_path, class:'btn btn-info col-xs-10 col-xs-offset-1' %>
				</div>
				<div class = "row-home">
					<%= link_to "Sign up", new_user_registration_path,class:'btn btn-success col-xs-10 col-xs-offset-1' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
  </head>

  <body>
    <!-- ヘッダー -->
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class= "nav nav-bar navbar-left">
      <h3 class="top"><span>Bookers</span></h3>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to " Home",user_path(current_user.id), class: "glyphicon glyphicon-home" %>
          </li>
          <li>
            <%=link_to " Users" ,users_path, class: "glyphicon glyphicon-link" %>
          </li>
          <li>
            <%=link_to " Books" ,books_path, class: "glyphicon glyphicon-book" %>
          </li>

          <li>
            <%=link_to " logout" , destroy_user_session_path, method: :delete ,class: "glyphicon glyphicon-log-out" %>
          </li>
        <% else %>
          <li>
            <%=link_to " Home" ,root_path, class: "glyphicon glyphicon-home" %>
          </li>

          <li>
            <%=link_to " About", home_about_path ,class: "glyphicon glyphicon-link" %>
          </li>

          <li>
            <%=link_to " sign up", new_user_registration_path ,class:"glyphicon glyphicon-edit" %>
           </li>
          <li>
            <%=link_to " login" ,new_user_session_path ,class: "glyphicon glyphicon-log-in"%>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

    <!-- ヘッダー -->




    <%= yield %>

    <!--フッター -->
    <footer>
      <div class ="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
              CopyRight Infratop.inc
          </div>
        </div>
      </div>
    </footer>
    <!-- フッター -->




  </body>
</html>

app/views/users/_info.html.erb
            <h2>User info</h2>
            <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                <table class="table table">
                    <tbody>
                        <tr>
                            <th>Name</th><td><%= user.name %></td>
                        </tr>
                        <tr>
                            <th>Introduction</th><td><%= user.introduction %></td>
                        </tr>
                    </tbody>
                </table>

                    <div class="edit-btn">
                    <%= link_to sanitize('<span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>') , edit_user_path(user) , class: "btn btn-default btn-block" %>
                    </div>

app/views/users/edit.html.erb
<div class = "container">

<div class ="edit">
<h2>User info</h2>

<div id="error_explanation">
        <% if @user.errors.any? %>
            <h2><%= @user.errors.count %> errors prohibited this obj from being saved:</h2>
                <ul>
                    <% @user.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
        <% end %>
    </div>

<%= form_for(@user) do |f| %>
    <div class="form-group has-icon">
        <label>Name</label><br>
        <%= f.text_field :name, autofocus: true, id:"inputEmail"%>
    </div>

	<div class="form-group has-icon">
    	<label>Image</label>
    	<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
	</div>

    <div class="form-group has-icon">
        <label>Introduction</label><br>
        <%= f.text_area :introduction, autofocus: true%>
    </div>

    <%= f.submit "Update User" %>
<% end %>

</div>
</div>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-3">

            <!-- プロフィール -->
            <%= render 'users/info', user: @user %>
            <!-- プロフィール -->

            <!-- 新規投稿 -->

            <%= render 'books/new', book: @book %>

            <!-- 新規投稿 -->

        </div>




            <!-- ユーザ一覧画面 -->
        <div class="col-xs-9">
            <h2>Users</h2>

                <table class ="table table">
                    <thead>
                        <tr>
                            <th>image</th> <th>name</th><th colspan="3"></th>
                        </tr>
                    </thead>

                   <tbody>
                            <% @users.each do |user| %>
                                <tr>
                                    <td>
                                        <%= attachment_image_tag user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
                                    </td>
                                    <td>
                                        <%= user.name %>
                                    </td>
                                    <td>
                                        <%= link_to "show", user_path(user.id) %>
                                    </td>
                                </tr>
                            <% end %>
                    </tbody>
                </table>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <!-- エラーメッセージ -->
    <div id="error_explanation">
        <% if @book.errors.any? %>
            <h2><%= @book.errors.count %>件のエラーが発生しました</h2>
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
        <% end %>
    </div>

    <div class="row">
        <div class="col-xs-3">

    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

    <% if flash[:notice3] %>
      <div class="flash">
        <%= flash[:notice3] %>
      </div>
    <% end %>

            <!-- プロフィール -->
            <%= render 'users/info', user: @user %>
            <!-- プロフィール -->

            <!-- 新規投稿 -->

            <%= render 'books/new', book: @book %>

            <!-- 新規投稿 -->

        </div>




            <!-- 投稿一覧画面 -->
        <div class="col-xs-9">
            <h2>Books</h2>

                <table class ="table table-hover">
                    <thead>
                        <tr>
                            <th></th><th>Title</th> <th>Opinion</th><th colspan="3"></th>
                        </tr>
                    </thead>

                   <tbody>
                            <% @books.each do |book| %>
                                <tr>
                                    <td><%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %></td>
                                    <td>
                                        <%= link_to "#{book.title}",book_path(book.id)%>
                                    </td>
                                    <td>
                                        <%= book.body %>
                                    </td>
                                </tr>
                            <% end %>
                    </tbody>
                </table>
        </div>
    </div>
</div>


            <!-- 投稿一覧画面 -->